name: Build Zip

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
jobs:
  build:
    timeout-minutes: 15

    runs-on: ubuntu-latest
    name: Build Zip

    strategy:
      matrix:
        php: ["8.0"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

    - name: Install PHP dependencies
      run: composer install --no-interaction --ignore-platform-reqs

    - name: Build Addon
      run: composer build wp2static-addon

    - name: Archive zip
      uses: actions/upload-artifact@v2
      with:
        name: Addon Zip
        path: ~/Downloads/wp2static-addon.zip